export const PROXY_BASE_API_PATH = '/api/langflow';

export const PROXY_CHAT_ENDPOINT_SUFFIX = '/chat';
export const PROXY_MESSAGES_ENDPOINT_SUFFIX = '/messages';
export const PROXY_FLOWS_CONFIG_ENDPOINT_SUFFIX = '/flows_config';

export const PROXY_CHAT_PATH = PROXY_BASE_API_PATH + PROXY_CHAT_ENDPOINT_SUFFIX;
export const PROXY_MESSAGES_PATH = PROXY_BASE_API_PATH + PROXY_MESSAGES_ENDPOINT_SUFFIX;
export const PROXY_FLOWS_PATH = PROXY_BASE_API_PATH + PROXY_FLOWS_CONFIG_ENDPOINT_SUFFIX;
